name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4

      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.3.0
        with:
          fetch-depth: 0

      - name: Set up Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Fetch all tags
        if: ${{ steps.release.outputs.release_created }}
        run: git fetch --tags

      - name: Run GoReleaser
        if: ${{ steps.release.outputs.release_created }}
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
        with:
          distribution: goreleaser
          version: ~> v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
