name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0

      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.3.0
        with:
          fetch-depth: 0

      - name: Set up Go
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Fetch all tags
        if: ${{ steps.release.outputs.release_created }}
        run: git fetch --tags

      - name: Run GoReleaser
        if: ${{ steps.release.outputs.release_created }}
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: ~> v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
